# ./docker-compose.test.yml
# From ./frappe-dokploy-compose
# docker-compose -f ./docker/erpnext/docker-compose.test-local.yml --env-file ./docker/erpnext/.env up -d
# --- YAML Anchors / Extensions ---
x-frappe-image-network-defaults: &frappe-image-network-defaults
  image: frappe/erpnext:v15
  networks:
    - frappe-network-test

x-frappe-service-defaults: &frappe-defaults
  <<: *frappe-image-network-defaults
  deploy:
    restart_policy:
      condition: on-failure

x-redis-defaults: &redis-defaults
  image: redis:6.2-alpine
  networks:
    - frappe-network-test
  deploy:
    restart_policy:
      condition: on-failure

# --- Services --- #
services:
  initial-setup-test:
    <<: *frappe-defaults
    user: "0:0"
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command: 
      - >
        bash /populate_frappe_code.sh;
        echo "✅ Container commands executed";
    volumes:
      - frappe-code-data-test:/mnt
      - ../../initial-setup-service/populate_frappe_code.sh:/populate_frappe_code.sh

  configurator-service-test:
    <<: *frappe-image-network-defaults
    depends_on:
      initial-setup-test:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash /run/configurator_setup.sh;
        echo "✅ Container commands executed";
    environment:
      ENV: -test
      DB_HOST: db-service-test
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache-service-test:6379
      REDIS_QUEUE: redis-queue-service-test:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - ../../configurator-service/configurator_setup.sh:/run/configurator_setup.sh
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs

  create-site-service-test:
    <<: *frappe-image-network-defaults
    depends_on:
      configurator-service-test:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash /run/create_site_setup.sh;
        bash /run/auto_setup_wizard.sh;
        bash /run/install_apps.sh erp-test.growatt.app '[
          {"name": "frappe_comment_agt", "url": "https://github.com/AnyGridTech/frappe_comment_agt", "branch": "develop"},
          {"name": "frappe_agt", "url": "https://github.com/AnyGridTech/frappe_agt", "branch": "develop"},
          {"name": "frappe_growatt_plant", "url": "https://github.com/AnyGridTech/frappe_growatt_plant", "branch": "develop"},
          {"name": "frappe_it_request", "url": "https://github.com/AnyGridTech/frappe_it_request", "branch": "develop"},
          {"name": "frappe_workflow_history", "url": "https://github.com/AnyGridTech/frappe_workflow_history", "branch": "develop"}
        ]';
        echo "✅ Container commands executed";
    volumes:
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs
      - ../../create-site-service/auto_setup_wizard.sh:/run/auto_setup_wizard.sh
      - ../../create-site-service/install_apps.sh:/run/install_apps.sh
      - ../../create-site-service/create_site_setup.sh:/run/create_site_setup.sh
    environment:
      ENV: -test
      SITE_NAME: erp-test.growatt.app
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  frontend-service-test:
    <<: *frappe-defaults
    networks:
      - frappe-network-test
    depends_on:
      create-site-service-test:
        condition: service_completed_successfully
    entrypoint: [bash, -c]
    command:
      - >
        bash /run/start_frontend.sh;
    environment:
      SITE_NAME: erp-test.growatt.app
      BACKEND: backend-service-test:8000
      FRAPPE_SITE_NAME_HEADER: erp-test.growatt.app
      SOCKETIO: websocket-service-test:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs
      - ../../frontend-service/start_frontend.sh:/run/start_frontend.sh

  backend-service-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bash /run/start_backend.sh;
    volumes:
      - ../../backend-service/start_backend.sh:/run/start_backend.sh
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db-service-test
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
  queue-long-service-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench worker --queue "long,default,short";
    volumes:
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs

  queue-short-service-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench worker --queue "default,short";
    volumes:
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs

  scheduler-service-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench schedule;
    volumes:
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-test:/home/frappe/frappe-bench/env
      - services-logs-data-test:/home/frappe/frappe-bench/logs

  websocket-service-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        node /home/frappe/frappe-bench/apps/frappe/socketio.js;
    volumes:
      - frappe-sites-data-test:/home/frappe/frappe-bench/sites
      - services-logs-data-test:/home/frappe/frappe-bench/logs
      - frappe-code-data-test:/home/frappe/frappe-bench/apps

  db-service-test:
    image: mariadb:10.6
    networks:
      - frappe-network-test
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost --password=$$MYSQL_ROOT_PASSWORD
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - frappe-db-data-test:/var/lib/mysql

  phpmyadmin-service-test:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db-service-test:
        condition: service_healthy
    networks:
      - frappe-network-test
    environment:
      PMA_HOST: db-service-test
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    links:
      - db-service-test 

  redis-queue-service-test:
    <<: *redis-defaults
    volumes:
      - frappe-redis-queue-data-test:/data

  redis-cache-service-test:
    <<: *redis-defaults
    volumes:
      - frappe-redis-cache-data-test:/data

volumes:
  services-logs-data-test:
  frappe-code-data-test:
  frappe-sites-data-test:
  frappe-env-data-test:
  frappe-db-data-test:
  frappe-redis-queue-data-test:
  frappe-redis-cache-data-test:

networks:
  frappe-network-test:
    driver: bridge

# --- End of Services --- #