version: "3"

services:
  backend:
    image: frappe/erpnext:v15.47.1
    networks:
      - frappe_network
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites
    env_file:
      - .env
    links:
      - redis-cache
      - redis-queue
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

  configurator:
    image: frappe/erpnext:v15.47.1
    networks:
      - frappe_network
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench setup requirements;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites

  create-site:
    image: frappe/erpnext:v15.47.1
    networks:
      - frappe_network
    links:
      - redis-cache
      - redis-queue
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - frappe-sites:/home/frappe/frappe-bench/sites

  frontend:
    image: frappe/erpnext:v15.47.1
    networks:
      - frappe_network
    depends_on:
      - websocket
    links:
      - redis-cache
      - redis-queue
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites
    ports:
      - "8080:8080"

  queue-long:
    image: frappe/erpnext:v15.47.1
    restart: always
    networks:
      - frappe_network
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites

  queue-short:
    image: frappe/erpnext:v15.47.1
    restart: always
    links:
      - redis-cache
      - redis-queue
    networks:
      - frappe_network
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    ports:
      - "6379:6379"
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    ports:
      - "6380:6379"
    volumes:
      - redis-cache-data:/data

  scheduler:
    image: frappe/erpnext:v15.47.1
    networks:
      - frappe_network
    command:
      - bench
      - schedule
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites

  websocket:
    image: frappe/erpnext:v15.47.1
    ports:
      - "9000:9000"
    networks:
      - frappe_network
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - frappe-code:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites:/home/frappe/frappe-bench/sites

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - frappe_network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/anygrid/data/mysql
      o: bind
  frappe-code:
    driver: local
    driver_opts:
      type: none
      device: /home/anygrid/code/frappe
      o: bind,mode=0777
  frappe-sites:
    driver: local
    driver_opts:
      type: none
      device: /home/anygrid/data/sites
      o: bind
  redis-queue-data:
    driver: local
    driver_opts:
      type: none
      device: /home/anygrid/data/redis-queue
      o: bind
  redis-cache-data:
    driver: local
    driver_opts:
      type: none
      device: /home/anygrid/data/redis-cache
      o: bind

networks:
  frappe_network:
    driver: bridge