# ./docker-compose.test.yml
# --- YAML Anchors / Extensions ---
x-frappe-image-network-defaults: &frappe-image-network-defaults
  image: frappe/erpnext:v15
  networks:
    - frappe-network-marco-test

x-frappe-service-defaults: &frappe-defaults
  <<: *frappe-image-network-defaults
  deploy:
    restart_policy:
      condition: on-failure

x-redis-defaults: &redis-defaults
  image: redis:6.2-alpine
  networks:
    - frappe-network-marco-test
  deploy:
    restart_policy:
      condition: on-failure

# --- Services --- #
services:
  initial-setup-marco-test:
    <<: *frappe-defaults
    user: "0:0"
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command: 
      - >
        bash /populate_frappe_code.sh;
        echo "✅ Container commands executed";
    volumes:
      - frappe-code-data-marco-test:/mnt/apps
      - ./initial-setup-service/populate_frappe_code.sh:/populate_frappe_code.sh

  configurator-service-marco-test:
    <<: *frappe-image-network-defaults
    depends_on:
      initial-setup-marco-test:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash ./configurator_setup.sh;
        echo "✅ Container commands executed";
    environment:
      DB_HOST: db-service-marco-test
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache-service-marco-test:6379
      REDIS_QUEUE: redis-queue-service-marco-test:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - ./configurator-service/configurator_setup.sh:/home/frappe/frappe-bench/configurator_setup.sh
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs

  create-site-service-marco-test:
    <<: *frappe-image-network-defaults
    depends_on:
      configurator-service-marco-test:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash ./create_site_setup.sh;
        bash ./auto_setup_wizard.sh;
        bash ./install_apps.sh;
        echo "✅ Container commands executed";
    volumes:
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs
      - ./create-site-service/auto_setup_wizard.sh:/home/frappe/frappe-bench/auto_setup_wizard.sh
      - ./create-site-service/install_apps.sh:/home/frappe/frappe-bench/install_apps.sh
      - ./create-site-service/create_site_setup.sh:/home/frappe/frappe-bench/create_site_setup.sh
    environment:
      SITE_NAME: erp-marco-test.growatt.app
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  frontend-service-marco-test:
    <<: *frappe-defaults
    networks:
      - frappe-network-marco-test
      - dokploy-network
    depends_on:
      create-site-service-marco-test:
        condition: service_completed_successfully
    entrypoint: [bash, -c]
    command:
      - >
        bash ./start_frontend.sh;
    environment:
      SITE_NAME: erp-marco-test.growatt.app
      BACKEND: backend-service-marco-test:8000
      FRAPPE_SITE_NAME_HEADER: erp-marco-test.growatt.app
      SOCKETIO: websocket-service-marco-test:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs
      - ./frontend-service/start_frontend.sh:/home/frappe/frappe-bench/start_frontend.sh

  backend-service-marco-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-marco-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bash ./start_backend.sh;
    volumes:
      - ./backend-service/start_backend.sh:/home/frappe/frappe-bench/start_backend.sh
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db-service-marco-test
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
  queue-long-service-marco-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-marco-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench worker --queue "long,default,short";
    volumes:
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs

  queue-short-service-marco-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-marco-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench worker --queue "default,short";
    volumes:
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs

  scheduler-service-marco-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-marco-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench schedule;
    volumes:
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps
      - frappe-env-data-marco-test:/home/frappe/frappe-bench/env
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs

  websocket-service-marco-test:
    <<: *frappe-defaults
    depends_on:
      create-site-service-marco-test:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        node /home/frappe/frappe-bench/apps/frappe/socketio.js;
    volumes:
      - frappe-sites-data-marco-test:/home/frappe/frappe-bench/sites
      - services-logs-data-marco-test:/home/frappe/frappe-bench/logs
      - frappe-code-data-marco-test:/home/frappe/frappe-bench/apps

  db-service-marco-test:
    image: mariadb:10.6
    networks:
      - frappe-network-marco-test
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost --password=$$MYSQL_ROOT_PASSWORD
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - frappe-db-data-marco-test:/var/lib/mysql

  phpmyadmin-service-marco-test:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db-service-marco-test:
        condition: service_healthy
    networks:
      - frappe-network-marco-test
      - dokploy-network
    environment:
      PMA_HOST: db-service-marco-test
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    links:
      - db-service-marco-test 

  redis-queue-service-marco-test:
    <<: *redis-defaults
    volumes:
      - frappe-redis-queue-data-marco-test:/data

  redis-cache-service-marco-test:
    <<: *redis-defaults
    volumes:
      - frappe-redis-cache-data-marco-test:/data

volumes:
  services-logs-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/frappe-bench/logs
      o: bind

  frappe-code-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/frappe-bench/apps
      o: bind,mode=0777

  frappe-sites-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/frappe-bench/sites
      o: bind
  
  frappe-env-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/frappe-bench/env
      o: bind

  frappe-db-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/maria-db/data
      o: bind

  frappe-redis-queue-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/redis-queue/data
      o: bind

  frappe-redis-cache-data-marco-test:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-marco-test/redis-cache/data
      o: bind

networks:
  frappe-network-marco-test:
    driver: bridge
  dokploy-network:
    external: true

# --- End of Services --- #

# Em caso de erro relacionado a pastas dos volumes não existirem, crie as pastas com o comando abaixo:
# sudo mkdir -p \
#   /home/frappe-marco-test/frappe-bench/logs \
#   /home/frappe-marco-test/frappe-bench/apps \
#   /home/frappe-marco-test/frappe-bench/sites \
#   /home/frappe-marco-test/frappe-bench/env \
#   /home/frappe-marco-test/maria-db/data \
#   /home/frappe-marco-test/redis-cache/data \
#   /home/frappe-marco-test/redis-queue/data  