version: "3"

# --- YAML Anchors / Extensions ---
x-frappe-image-network-defaults: &frappe-image-network-defaults
  image: frappe/erpnext:v15.71.1
  networks:
    - frappe-network-prod

x-frappe-service-defaults: &frappe-defaults
  <<: *frappe-image-network-defaults
  deploy:
    restart_policy:
      condition: on-failure

x-redis-defaults: &redis-defaults
  image: redis:6.2-alpine
  networks:
    - frappe-network-prod
  deploy:
    restart_policy:
      condition: on-failure

# --- Services --- #
services:
  backend-service-prod:
    <<: *frappe-defaults
    volumes:
      - frappe-code-data-prod:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db-service-prod
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  frontend-service-prod:
    <<: *frappe-defaults
    networks:
      - frappe-network-prod
      - dokploy-network
    depends_on:
      - websocket-service-prod
    command: [nginx-entrypoint.sh]
    environment:
      SITE_NAME: ${SITE_NAME}
      BACKEND: backend-service-prod:8000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
      SOCKETIO: websocket-service-prod:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs

  configurator-service-prod:
    <<: *frappe-image-network-defaults
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db-service-prod
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache-service-prod:6379
      REDIS_QUEUE: redis-queue-service-prod:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - frappe-code-data-prod:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs

  create-site-service-prod:
    <<: *frappe-image-network-defaults
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        wait-for-it -t 120 db-service-prod:3306;
        wait-for-it -t 120 redis-cache-service-prod:6379;
        wait-for-it -t 120 redis-queue-service-prod:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] &&
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] &&
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s` - start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1;
          fi;
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=$${MYSQL_ROOT_PASSWORD} --db-root-username=root --db-root-password=$${MYSQL_ROOT_PASSWORD} --install-app erpnext --set-default $${SITE_NAME}
    volumes:
      - frappe-code-data-prod:/home/frappe/frappe-bench/apps/frappe
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs
    environment:
      SITE_NAME: ${SITE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db-service-prod:
    image: mariadb:10.6
    networks:
      - frappe-network-prod
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost --password=${MYSQL_ROOT_PASSWORD}
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 15s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - frappe-db-data-prod:/var/lib/mysql

  phpmyadmin-service-prod:
    image: phpmyadmin/phpmyadmin
    networks:
      - frappe-network-prod
      - dokploy-network
    environment:
      PMA_HOST: db-service-prod
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    depends_on:
      db-service-prod:
        condition: service_healthy
    links:
      - db-service-prod 

  queue-long-service-prod:
    <<: *frappe-defaults
    command: [bench, worker, --queue, "long,default,short"]
    volumes:
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs

  queue-short-service-prod:
    <<: *frappe-defaults
    command: [bench, worker, --queue, "short,default"]
    volumes:
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs

  scheduler-service-prod:
    <<: *frappe-defaults
    command: [bench, schedule]
    volumes:
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs

  websocket-service-prod:
    <<: *frappe-defaults
    command: [node, /home/frappe/frappe-bench/apps/frappe/socketio.js]
    volumes:
      - frappe-sites-data-prod:/home/frappe/frappe-bench/sites
      - services-logs-data-prod:/home/frappe/frappe-bench/logs

  redis-queue-service-prod:
    <<: *redis-defaults
    volumes:
      - frappe-redis-queue-data-prod:/data

  redis-cache-service-prod:
    <<: *redis-defaults
    volumes:
      - frappe-redis-cache-data-prod:/data

volumes:
  services-logs-data-prod:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-prod/frappe-bench/logs
      o: bind

  frappe-code-data-prod:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-prod/frappe-bench/apps/frappe
      o: bind,mode=0777

  frappe-sites-data-prod:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-prod/frappe-bench/sites
      o: bind

  frappe-db-data-prod:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-prod/maria-db/data
      o: bind

  frappe-redis-queue-data-prod:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-prod/redis-queue/data
      o: bind

  frappe-redis-cache-data-prod:
    driver: local
    driver_opts:
      type: none
      device: /home/frappe-prod/redis-cache/data
      o: bind

networks:
  frappe-network-prod:
    driver: bridge
  dokploy-network:
    external: true

# --- End of Services --- #

# Em caso de erro relacionado a pastas dos volumes nÃ£o existirem, crie as pastas com o comando abaixo:
# sudo mkdir -p \
#   /home/frappe-prod/frappe-bench/logs \
#   /home/frappe-prod/frappe-bench/apps/frappe \
#   /home/frappe-prod/frappe-bench/sites \
#   /home/frappe-prod/maria-db/data \
#   /home/frappe-prod/redis-cache/data \
#   /home/frappe-prod/redis-queue/data  