# ./docker-compose.test.yml
# --- YAML Anchors / Extensions ---
x-frappe-image-network-defaults: &frappe-image-network-defaults
  image: frappe/erpnext:v15
  networks:
    - frappe-network-codewin

x-frappe-service-defaults: &frappe-defaults
  <<: *frappe-image-network-defaults
  deploy:
    restart_policy:
      condition: on-failure

x-redis-defaults: &redis-defaults
  image: redis:6.2-alpine
  networks:
    - frappe-network-codewin
  deploy:
    restart_policy:
      condition: on-failure

# --- Services --- #
services:
  configurator-service-codewin:
    <<: *frappe-image-network-defaults
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash ./configurator_setup.sh;
        echo "✅ Container commands executed";
    environment:
      ENV: -codewin
      DB_HOST: db-service-codewin
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache-service-codewin:6379
      REDIS_QUEUE: redis-queue-service-codewin:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - ./configurator-service/configurator_setup.sh:/home/frappe/frappe-bench/configurator_setup.sh
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs

  create-site-service-codewin:
    <<: *frappe-image-network-defaults
    depends_on:
      configurator-service-codewin:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash ./create_site_setup.sh;
        bash ./auto_setup_wizard.sh;
        bash ./install_apps.sh;
        echo "✅ Container commands executed";
    volumes:
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs
      - ./create-site-service/auto_setup_wizard.sh:/home/frappe/frappe-bench/auto_setup_wizard.sh
      - ./create-site-service/install_apps.sh:/home/frappe/frappe-bench/install_apps.sh
      - ./create-site-service/create_site_setup.sh:/home/frappe/frappe-bench/create_site_setup.sh
    environment:
      ENV: -codewin
      SITE_NAME: erp-codewin.growatt.app
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  frontend-service-codewin:
    <<: *frappe-defaults
    networks:
      - frappe-network-codewin
    depends_on:
      create-site-service-codewin:
        condition: service_completed_successfully
    entrypoint: [bash, -c]
    command:
      - >
        bash ./start_frontend.sh;
    environment:
      SITE_NAME: erp-codewin.growatt.app
      BACKEND: backend-service-codewin:8000
      FRAPPE_SITE_NAME_HEADER: erp-codewin.growatt.app
      SOCKETIO: websocket-service-codewin:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs
      - ./frontend-service/start_frontend.sh:/home/frappe/frappe-bench/start_frontend.sh

  backend-service-codewin:
    <<: *frappe-defaults
    depends_on:
      create-site-service-codewin:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bash ./start_backend.sh;
    volumes:
      - ./backend-service/start_backend.sh:/home/frappe/frappe-bench/start_backend.sh
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db-service-codewin
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
  queue-long-service-codewin:
    <<: *frappe-defaults
    depends_on:
      create-site-service-codewin:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench worker --queue "long,default,short";
    volumes:
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs

  queue-short-service-codewin:
    <<: *frappe-defaults
    depends_on:
      create-site-service-codewin:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench worker --queue "default,short";
    volumes:
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs

  scheduler-service-codewin:
    <<: *frappe-defaults
    depends_on:
      create-site-service-codewin:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bench schedule;
    volumes:
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps
      - frappe-env-data-codewin:/home/frappe/frappe-bench/env
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs

  websocket-service-codewin:
    <<: *frappe-defaults
    depends_on:
      create-site-service-codewin:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        node /home/frappe/frappe-bench/apps/frappe/socketio.js;
    volumes:
      - frappe-sites-data-codewin:/home/frappe/frappe-bench/sites
      - services-logs-data-codewin:/home/frappe/frappe-bench/logs
      - frappe-code-data-codewin:/home/frappe/frappe-bench/apps

  db-service-codewin:
    image: mariadb:10.6
    networks:
      - frappe-network-codewin
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost --password=$$MYSQL_ROOT_PASSWORD
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - frappe-db-data-codewin:/var/lib/mysql

  phpmyadmin-service-codewin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db-service-codewin:
        condition: service_healthy
    networks:
      - frappe-network-codewin
    environment:
      PMA_HOST: db-service-codewin
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    links:
      - db-service-codewin 

  redis-queue-service-codewin:
    <<: *redis-defaults
    volumes:
      - frappe-redis-queue-data-codewin:/data

  redis-cache-service-codewin:
    <<: *redis-defaults
    volumes:
      - frappe-redis-cache-data-codewin:/data

volumes:
  services-logs-data-codewin:
  frappe-code-data-codewin:
  frappe-sites-data-codewin:
  frappe-env-data-codewin:
  frappe-db-data-codewin:
  frappe-redis-queue-data-codewin:
  frappe-redis-cache-data-codewin:

networks:
  frappe-network-codewin:
    driver: bridge