# ./.devcontainer/docker-compose.yml
# --- YAML Anchors / Extensions ---
x-frappe-image-network-defaults: &frappe-image-network-defaults
  image: frappe/erpnext:v15
  networks:
    - frappe-network-codecontainer

x-frappe-service-defaults: &frappe-defaults
  <<: *frappe-image-network-defaults
  deploy:
    restart_policy:
      condition: on-failure

x-redis-defaults: &redis-defaults
  image: redis:6.2-alpine
  networks:
    - frappe-network-codecontainer
  deploy:
    restart_policy:
      condition: on-failure

# --- Services --- #
services:
  configurator-service-codecontainer:
    <<: *frappe-image-network-defaults
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash ./configurator_setup.sh;
        echo "✅ Container commands executed";
    environment:
      ENV: -codecontainer
      DB_HOST: db-service-codecontainer
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache-service-codecontainer:6379
      REDIS_QUEUE: redis-queue-service-codecontainer:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - ../configurator-service/configurator_setup.sh:/home/frappe/frappe-bench/configurator_setup.sh
      - ./frappe-bench:/home/frappe/frappe-bench/sites
      - ./frappe-bench:/home/frappe/frappe-bench/apps
      - ./frappe-bench:/home/frappe/frappe-bench/env
      - ./frappe-bench:/home/frappe/frappe-bench/logs

  create-site-service-codecontainer:
    <<: *frappe-image-network-defaults
    depends_on:
      configurator-service-codecontainer:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    entrypoint: [bash, -c]
    command:
      - >
        bash ./create_site_setup.sh;
        bash ./auto_setup_wizard.sh;
        bash ./install_apps.sh erp-codecontainer.growatt.app '[]';
        echo "✅ Container commands executed";
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench/sites
      - ./frappe-bench:/home/frappe/frappe-bench/apps
      - ./frappe-bench:/home/frappe/frappe-bench/env
      - ./frappe-bench:/home/frappe/frappe-bench/logs
      - ../create-site-service/auto_setup_wizard.sh:/home/frappe/frappe-bench/auto_setup_wizard.sh
      - ../create-site-service/install_apps.sh:/home/frappe/frappe-bench/install_apps.sh
      - ../create-site-service/create_site_setup.sh:/home/frappe/frappe-bench/create_site_setup.sh
    environment:
      ENV: -codecontainer
      SITE_NAME: erp-codecontainer.growatt.app
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  workspace-service-codecontainer:
    <<: *frappe-defaults
    networks:
      - frappe-network-codecontainer
    depends_on:
      create-site-service-codecontainer:
        condition: service_completed_successfully
    working_dir: /workspace/development
    command: ["sleep", "infinity"]
    volumes:
      - ../frappe-bench:/home/frappe/frappe-bench

  backend-service-codecontainer:
    <<: *frappe-defaults
    depends_on:
      create-site-service-codecontainer:
        condition: service_completed_successfully
    working_dir: /home/frappe/frappe-bench
    entrypoint: [bash, -c]
    command: 
      - >
        bash ./start_backend.sh dev;
    volumes:
      - ../backend-service/start_backend.sh:/home/frappe/frappe-bench/start_backend.sh
      - ./frappe-bench:/home/frappe/frappe-bench/sites
      - ./frappe-bench:/home/frappe/frappe-bench/apps
      - ./frappe-bench:/home/frappe/frappe-bench/env
      - ./frappe-bench:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db-service-codecontainer
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db-service-codecontainer:
    image: mariadb:10.6
    networks:
      - frappe-network-codecontainer
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost --password=$$MYSQL_ROOT_PASSWORD
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - frappe-db-data-codecontainer:/var/lib/mysql

  phpmyadmin-service-codecontainer:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db-service-codecontainer:
        condition: service_healthy
    networks:
      - frappe-network-codecontainer
    environment:
      PMA_HOST: db-service-codecontainer
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    links:
      - db-service-codecontainer 

  redis-queue-service-codecontainer:
    <<: *redis-defaults
    volumes:
      - frappe-redis-queue-data-codecontainer:/data

  redis-cache-service-codecontainer:
    <<: *redis-defaults
    volumes:
      - frappe-redis-cache-data-codecontainer:/data

volumes:
  frappe-db-data-codecontainer:
  frappe-redis-queue-data-codecontainer:
  frappe-redis-cache-data-codecontainer:

networks:
  frappe-network-codecontainer:
    driver: bridge